name: Validate PR Naming and Handle Labeling

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate-pr:
    name: Validate PR Naming and Add Label
    runs-on: ubuntu-latest

    outputs:
      valid_pr: ${{ steps.check_pr.outputs.valid_pr }}

    steps:
      - name: Check PR Naming Convention
        id: check_pr
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^gokul# ]]; then
            echo "PR title does not match the required convention. Adding label 'no work item found'."
            echo "::set-output name=valid_pr::false"
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
              -d '{"labels":["no work item found"]}'
          else
            echo "PR title validation passed."
            echo "::set-output name=valid_pr::true"
          fi
        shell: bash

  check-label:
    name: Check for Added Label and Fail if Found
    runs-on: ubuntu-latest
    needs: validate-pr
    if: ${{ needs.validate-pr.outputs.valid_pr == 'false' }}  # Only run if the PR naming is invalid

    steps:
      - name: Fetch PR Labels
        id: fetch_labels
        run: |
          curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels > labels.json
          cat labels.json

      - name: Check if "no work item found" Label Exists
        run: |
          if grep -q '"name": "no work item found"' labels.json; then
            echo "PR labeled as 'no work item found'. Failing the job."
            exit 1
          else
            echo "Label 'no work item found' not found. Passing the job."
          fi
